#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

ts="${RUN_TS:-$(date -u +%Y%m%d_%H%M%S)}"

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3}"
export MODEL="${MODEL:-/workspace/models/Qwen3-8B}"
export AGENT_KIND="${AGENT_KIND:-qwen}"

export ADV_ESTIMATOR="${ADV_ESTIMATOR:-gae}"
export TRAIN_EPISODES="${TRAIN_EPISODES:-512}"
export VAL_EPISODES="${VAL_EPISODES:-32}"
export TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-8}"
export ROLLOUT_N="${ROLLOUT_N:-4}"
export TOTAL_EPOCHS="${TOTAL_EPOCHS:-2}"

export N_GPUS_PER_NODE="${N_GPUS_PER_NODE:-4}"
export TENSOR_MODEL_PARALLEL_SIZE="${TENSOR_MODEL_PARALLEL_SIZE:-4}"
export N_RUNNERS="${N_RUNNERS:-1}"

export MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-4096}"
export MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-64}"
export PPO_MINI_BATCH_SIZE="${PPO_MINI_BATCH_SIZE:-8}"
export PPO_MICRO_BATCH_SIZE_PER_GPU="${PPO_MICRO_BATCH_SIZE_PER_GPU:-1}"
export CRITIC_PPO_MICRO_BATCH_SIZE_PER_GPU="${CRITIC_PPO_MICRO_BATCH_SIZE_PER_GPU:-1}"
export CRITIC_FORWARD_MICRO_BATCH_SIZE_PER_GPU="${CRITIC_FORWARD_MICRO_BATCH_SIZE_PER_GPU:-1}"
export ROLLOUT_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU="${ROLLOUT_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-1}"
export REF_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU="${REF_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-1}"
export CRITIC_PPO_MAX_TOKEN_LEN_PER_GPU="${CRITIC_PPO_MAX_TOKEN_LEN_PER_GPU:-12288}"
export MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-8192}"
export MAX_NUM_SEQS="${MAX_NUM_SEQS:-64}"
export GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-0.35}"

export LR="${LR:-1e-6}"
export CRITIC_LR="${CRITIC_LR:-5e-6}"
export TEMPERATURE="${TEMPERATURE:-0.7}"
export TOP_P="${TOP_P:-0.95}"

export LORA_RANK="${LORA_RANK:-64}"
export LORA_ALPHA="${LORA_ALPHA:-128}"
export CRITIC_LORA_RANK="${CRITIC_LORA_RANK:-0}"
export CRITIC_LORA_ALPHA="${CRITIC_LORA_ALPHA:-16}"
export PARAM_OFFLOAD="${PARAM_OFFLOAD:-true}"
export OPTIMIZER_OFFLOAD="${OPTIMIZER_OFFLOAD:-true}"
export CRITIC_PARAM_OFFLOAD="${CRITIC_PARAM_OFFLOAD:-true}"
export CRITIC_OPTIMIZER_OFFLOAD="${CRITIC_OPTIMIZER_OFFLOAD:-true}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"

export REWARD_MODE="${REWARD_MODE:-auto}"
export ENV_KWARGS="${ENV_KWARGS:-{\"marshal_dense_reward\": true, \"marshal_fuse_penalty\": 0.25, \"marshal_invalid_penalty\": -0.05}}"

export SAVE_FREQ="${SAVE_FREQ:-16}"
export TEST_FREQ="${TEST_FREQ:-16}"
export LOGGER="${LOGGER:-console}"
export PROJECT_NAME="${PROJECT_NAME:-agent_lightning_hanabi}"
export EXPERIMENT_NAME="${EXPERIMENT_NAME:-hanabi_ppo4_formal_${ts}}"
export OUTPUT_DIR="${OUTPUT_DIR:-$ROOT_DIR/checkpoints/$PROJECT_NAME/$EXPERIMENT_NAME}"

mkdir -p "$ROOT_DIR/logs" "$OUTPUT_DIR"

exec bash "$ROOT_DIR/tools/train/train_agent_lightning_hanabi_verl.sh" "$@"
