#!/usr/bin/env bash
set -euo pipefail

# Hanabi wrapper (simple): external vLLM rollout server + ms-swift GRPO base.
#
# Usage example:
#   CUDA_VISIBLE_DEVICES=4,5,6,7 \
#   NPROC_PER_NODE=4 \
#   VLLM_SERVER_HOST=127.0.0.1,127.0.0.1,127.0.0.1,127.0.0.1 \
#   VLLM_SERVER_PORT=8000,8001,8002,8003 \
#   VLLM_SERVER_GROUP_PORT=51216,51217,51218,51219 \
#   NUM_GENERATIONS=16 \
#   GENERATION_BATCH_SIZE=64 \
#   MAX_LENGTH=4096 \
#   MAX_COMPLETION_LENGTH=64 \
#   MAX_STEPS=1000 \
#   SAVE_STEPS=500 \
#   bash tools/train/train_grpo_hanabi_server_simple.sh

if [ -z "${MODEL:-}" ]; then
  if [ -d "/workspace/models/Qwen3-8B" ]; then
    MODEL="/workspace/models/Qwen3-8B"
  else
    MODEL="Qwen/Qwen3-8B"
  fi
fi

DATASET="${DATASET:-data/hanabi.grpo.jsonl}"
OUTPUT_DIR="${OUTPUT_DIR:-output/qwen3-8b-hanabi-grpo}"

CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-4,5,6,7}"
NPROC_PER_NODE="${NPROC_PER_NODE:-4}"

NUM_GENERATIONS="${NUM_GENERATIONS:-8}"
GENERATION_BATCH_SIZE="${GENERATION_BATCH_SIZE:-16}"
STEPS_PER_GENERATION="${STEPS_PER_GENERATION:-}"
MAX_LENGTH="${MAX_LENGTH:-4096}"
MAX_COMPLETION_LENGTH="${MAX_COMPLETION_LENGTH:-64}"
NUM_TRAIN_EPOCHS="${NUM_TRAIN_EPOCHS:-}"
MAX_STEPS="${MAX_STEPS:-1000}"
SAVE_STEPS="${SAVE_STEPS:-500}"
MAX_TURNS="${MAX_TURNS:-}"
LOG_COMPLETIONS="${LOG_COMPLETIONS:-true}"

VLLM_SERVER_HOST="${VLLM_SERVER_HOST:-127.0.0.1}"
VLLM_SERVER_PORT="${VLLM_SERVER_PORT:-8000}"
VLLM_SERVER_GROUP_PORT="${VLLM_SERVER_GROUP_PORT:-}"
VLLM_SERVER_TIMEOUT="${VLLM_SERVER_TIMEOUT:-}"

REPORT_TO="${REPORT_TO:-wandb}"
RUN_NAME="${RUN_NAME:-grpo-hanabi}"
EXTRA_SWIFT_ARGS="${EXTRA_SWIFT_ARGS:-}"

NCCL_P2P_DISABLE="${NCCL_P2P_DISABLE:-0}"
NCCL_IB_DISABLE="${NCCL_IB_DISABLE:-0}"
DRY_RUN="${DRY_RUN:-false}"

MODEL="$MODEL" \
DATASET="$DATASET" OUTPUT_DIR="$OUTPUT_DIR" \
CUDA_VISIBLE_DEVICES="$CUDA_VISIBLE_DEVICES" NPROC_PER_NODE="$NPROC_PER_NODE" \
NUM_GENERATIONS="$NUM_GENERATIONS" GENERATION_BATCH_SIZE="$GENERATION_BATCH_SIZE" \
STEPS_PER_GENERATION="$STEPS_PER_GENERATION" \
MAX_LENGTH="$MAX_LENGTH" MAX_COMPLETION_LENGTH="$MAX_COMPLETION_LENGTH" \
NUM_TRAIN_EPOCHS="$NUM_TRAIN_EPOCHS" MAX_STEPS="$MAX_STEPS" SAVE_STEPS="$SAVE_STEPS" \
MAX_TURNS="$MAX_TURNS" LOG_COMPLETIONS="$LOG_COMPLETIONS" \
USE_VLLM=true VLLM_MODE=server \
VLLM_SERVER_HOST="$VLLM_SERVER_HOST" VLLM_SERVER_PORT="$VLLM_SERVER_PORT" \
VLLM_SERVER_GROUP_PORT="$VLLM_SERVER_GROUP_PORT" VLLM_SERVER_TIMEOUT="$VLLM_SERVER_TIMEOUT" \
REPORT_TO="$REPORT_TO" RUN_NAME="$RUN_NAME" \
REWARD_FUNCS= EXTERNAL_PLUGINS= \
EXTRA_SWIFT_ARGS="$EXTRA_SWIFT_ARGS" \
NCCL_P2P_DISABLE="$NCCL_P2P_DISABLE" NCCL_IB_DISABLE="$NCCL_IB_DISABLE" \
DRY_RUN="$DRY_RUN" \
bash tools/train/train_grpo_base.sh
