#!/usr/bin/env bash
set -euo pipefail

# Canonical Hanabi GRPO wrapper.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=tools/train/_common.sh
source "$SCRIPT_DIR/_common.sh"

RLHF_TYPE="${RLHF_TYPE:-grpo}"
if [ "$RLHF_TYPE" != "grpo" ]; then
  echo "train_hanabi_rlhf_simple.sh only supports RLHF_TYPE=grpo." >&2
  exit 1
fi

MODEL="${MODEL:-$(resolve_default_qwen3_8b_model)}"
DATASET="${DATASET:-data/hanabi.grpo.jsonl}"
SWIFT_BIN="${SWIFT_BIN:-}"
ADAPTERS="${ADAPTERS:-}"
ENABLE_THINKING="${ENABLE_THINKING:-}"
LEARNING_RATE="${LEARNING_RATE:-}"
BETA="${BETA:-}"
EXTRA_SWIFT_ARGS="${EXTRA_SWIFT_ARGS:-}"
EXTERNAL_PLUGINS="${EXTERNAL_PLUGINS:-}"
REPORT_TO="${REPORT_TO:-wandb}"
NCCL_P2P_DISABLE="${NCCL_P2P_DISABLE:-1}"
NCCL_IB_DISABLE="${NCCL_IB_DISABLE:-1}"
DRY_RUN="${DRY_RUN:-false}"

OUTPUT_DIR="${OUTPUT_DIR:-output/qwen3-8b-hanabi-grpo}"
CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-4,5,6,7}"
NPROC_PER_NODE="${NPROC_PER_NODE:-4}"
NUM_GENERATIONS="${NUM_GENERATIONS:-8}"
GENERATION_BATCH_SIZE="${GENERATION_BATCH_SIZE:-16}"
STEPS_PER_GENERATION="${STEPS_PER_GENERATION:-}"
MAX_LENGTH="${MAX_LENGTH:-4096}"
MAX_COMPLETION_LENGTH="${MAX_COMPLETION_LENGTH:-64}"
NUM_TRAIN_EPOCHS="${NUM_TRAIN_EPOCHS:-}"
MAX_STEPS="${MAX_STEPS:-1000}"
SAVE_STEPS="${SAVE_STEPS:-500}"
MAX_TURNS="${MAX_TURNS:-}"
LOG_COMPLETIONS="${LOG_COMPLETIONS:-true}"
VLLM_SERVER_HOST="${VLLM_SERVER_HOST:-127.0.0.1}"
VLLM_SERVER_PORT="${VLLM_SERVER_PORT:-8000}"
VLLM_SERVER_GROUP_PORT="${VLLM_SERVER_GROUP_PORT:-}"
VLLM_SERVER_TIMEOUT="${VLLM_SERVER_TIMEOUT:-}"
REF_ADAPTERS="${REF_ADAPTERS:-$ADAPTERS}"
ASYNC_GENERATE="${ASYNC_GENERATE:-}"
COMPLETION_LENGTH_LIMIT_SCOPE="${COMPLETION_LENGTH_LIMIT_SCOPE:-}"
VLLM_SERVER_PASS_DATASET="${VLLM_SERVER_PASS_DATASET:-}"
SOFT_MAX_LENGTH="${SOFT_MAX_LENGTH:-}"
OVERLONG_FILTER="${OVERLONG_FILTER:-}"

exec env \
  RLHF_TYPE=grpo \
  MODEL="$MODEL" \
  DATASET="$DATASET" OUTPUT_DIR="$OUTPUT_DIR" \
  CUDA_VISIBLE_DEVICES="$CUDA_VISIBLE_DEVICES" NPROC_PER_NODE="$NPROC_PER_NODE" \
  USE_VLLM=true VLLM_MODE=server \
  NUM_GENERATIONS="$NUM_GENERATIONS" GENERATION_BATCH_SIZE="$GENERATION_BATCH_SIZE" \
  STEPS_PER_GENERATION="$STEPS_PER_GENERATION" \
  MAX_LENGTH="$MAX_LENGTH" MAX_COMPLETION_LENGTH="$MAX_COMPLETION_LENGTH" \
  NUM_TRAIN_EPOCHS="$NUM_TRAIN_EPOCHS" MAX_STEPS="$MAX_STEPS" SAVE_STEPS="$SAVE_STEPS" \
  MAX_TURNS="$MAX_TURNS" LOG_COMPLETIONS="$LOG_COMPLETIONS" \
  VLLM_SERVER_HOST="$VLLM_SERVER_HOST" VLLM_SERVER_PORT="$VLLM_SERVER_PORT" \
  VLLM_SERVER_GROUP_PORT="$VLLM_SERVER_GROUP_PORT" VLLM_SERVER_TIMEOUT="$VLLM_SERVER_TIMEOUT" \
  REPORT_TO="$REPORT_TO" RUN_NAME="${RUN_NAME:-grpo-hanabi}" \
  SWIFT_BIN="$SWIFT_BIN" ADAPTERS="$ADAPTERS" REF_ADAPTERS="$REF_ADAPTERS" \
  ENABLE_THINKING="$ENABLE_THINKING" LEARNING_RATE="$LEARNING_RATE" BETA="$BETA" \
  ASYNC_GENERATE="$ASYNC_GENERATE" COMPLETION_LENGTH_LIMIT_SCOPE="$COMPLETION_LENGTH_LIMIT_SCOPE" \
  VLLM_SERVER_PASS_DATASET="$VLLM_SERVER_PASS_DATASET" SOFT_MAX_LENGTH="$SOFT_MAX_LENGTH" \
  OVERLONG_FILTER="$OVERLONG_FILTER" \
  REWARD_FUNCS= EXTERNAL_PLUGINS="$EXTERNAL_PLUGINS" \
  EXTRA_SWIFT_ARGS="$EXTRA_SWIFT_ARGS" \
  NCCL_P2P_DISABLE="$NCCL_P2P_DISABLE" NCCL_IB_DISABLE="$NCCL_IB_DISABLE" \
  DRY_RUN="$DRY_RUN" \
  bash "$SCRIPT_DIR/train_rlhf_base.sh"
