#!/usr/bin/env bash
set -euo pipefail

# Simple Hanabi GRPO train launcher (external vLLM server mode).
# No NO_PROXY auto patch / no auto group-port probing / no NCCL forced fallback.
#
# Typical 8xH800 split:
#   rollout: GPUs 0,1,2,3
#   train  : GPUs 4,5,6,7
#
# Usage:
#   CUDA_VISIBLE_DEVICES=4,5,6,7 \
#   NPROC_PER_NODE=4 \
#   VLLM_SERVER_HOST=127.0.0.1 \
#   VLLM_SERVER_PORT=8000 \
#   NUM_GENERATIONS=8 \
#   GENERATION_BATCH_SIZE=32 \
#   MAX_LENGTH=18000 \
#   MAX_COMPLETION_LENGTH=18000 \
#   MAX_STEPS=1000 \
#   bash tools/train/train_grpo_hanabi_server_simple.sh

if [ -z "${MODEL:-}" ]; then
  if [ -d "/workspace/models/Qwen3-8B" ]; then
    MODEL="/workspace/models/Qwen3-8B"
  else
    MODEL="Qwen/Qwen3-8B"
  fi
else
  MODEL="${MODEL}"
fi

DATASET="${DATASET:-data/hanabi.grpo.jsonl}"
OUTPUT_DIR="${OUTPUT_DIR:-output/qwen3-8b-hanabi-grpo}"

CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-4,5,6,7}"
NPROC_PER_NODE="${NPROC_PER_NODE:-4}"

NUM_GENERATIONS="${NUM_GENERATIONS:-8}"
GENERATION_BATCH_SIZE="${GENERATION_BATCH_SIZE:-32}"
MAX_LENGTH="${MAX_LENGTH:-18000}"
MAX_COMPLETION_LENGTH="${MAX_COMPLETION_LENGTH:-18000}"
MAX_STEPS="${MAX_STEPS:-1000}"
NUM_TRAIN_EPOCHS="${NUM_TRAIN_EPOCHS:-}"

VLLM_SERVER_HOST="${VLLM_SERVER_HOST:-127.0.0.1}"
VLLM_SERVER_PORT="${VLLM_SERVER_PORT:-8000}"
VLLM_SERVER_GROUP_PORT="${VLLM_SERVER_GROUP_PORT:-}"

REPORT_TO="${REPORT_TO:-wandb}"
RUN_NAME="${RUN_NAME:-grpo-hanabi}"
WANDB_PROJECT="${WANDB_PROJECT:-mindgames}"
WANDB_ENTITY="${WANDB_ENTITY:-}"
WANDB_MODE="${WANDB_MODE:-online}"
WANDB_LOG_MODEL="${WANDB_LOG_MODEL:-checkpoint}"
WANDB_WATCH="${WANDB_WATCH:-false}"
WANDB_NAME="${WANDB_NAME:-$RUN_NAME}"

PUSH_TO_HUB="${PUSH_TO_HUB:-false}"
USE_HF="${USE_HF:-false}"
HF_TOKEN="${HF_TOKEN:-}"
HF_REPO_ID="${HF_REPO_ID:-}"
HUB_STRATEGY="${HUB_STRATEGY:-end}"
HUB_PRIVATE_REPO="${HUB_PRIVATE_REPO:-false}"

NCCL_P2P_DISABLE="${NCCL_P2P_DISABLE:-0}"
NCCL_IB_DISABLE="${NCCL_IB_DISABLE:-0}"

REPORT_TO="$REPORT_TO" RUN_NAME="$RUN_NAME" WANDB_PROJECT="$WANDB_PROJECT" \
WANDB_ENTITY="$WANDB_ENTITY" WANDB_MODE="$WANDB_MODE" \
WANDB_LOG_MODEL="$WANDB_LOG_MODEL" WANDB_WATCH="$WANDB_WATCH" WANDB_NAME="$WANDB_NAME" \
CUDA_VISIBLE_DEVICES="$CUDA_VISIBLE_DEVICES" NPROC_PER_NODE="$NPROC_PER_NODE" \
NCCL_P2P_DISABLE="$NCCL_P2P_DISABLE" NCCL_IB_DISABLE="$NCCL_IB_DISABLE" \
MODEL="$MODEL" \
VLLM_MODE=server \
VLLM_SERVER_HOST="$VLLM_SERVER_HOST" VLLM_SERVER_PORT="$VLLM_SERVER_PORT" \
VLLM_SERVER_GROUP_PORT="$VLLM_SERVER_GROUP_PORT" \
DATASET="$DATASET" OUTPUT_DIR="$OUTPUT_DIR" \
NUM_GENERATIONS="$NUM_GENERATIONS" GENERATION_BATCH_SIZE="$GENERATION_BATCH_SIZE" \
MAX_LENGTH="$MAX_LENGTH" MAX_COMPLETION_LENGTH="$MAX_COMPLETION_LENGTH" \
NUM_TRAIN_EPOCHS="$NUM_TRAIN_EPOCHS" MAX_STEPS="$MAX_STEPS" \
PUSH_TO_HUB="$PUSH_TO_HUB" USE_HF="$USE_HF" HUB_TOKEN="$HF_TOKEN" HUB_MODEL_ID="$HF_REPO_ID" \
HUB_STRATEGY="$HUB_STRATEGY" HUB_PRIVATE_REPO="$HUB_PRIVATE_REPO" \
REWARD_FUNCS= EXTERNAL_PLUGINS= \
bash tools/train/train_grpo_msswift.sh
