#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

ROLLOUT_SESSION="${ROLLOUT_SESSION:-hanabi_rollout_no_think}"
TRAIN_SESSION="${TRAIN_SESSION:-hanabi_train_no_think}"

MODEL="${MODEL:-/workspace/models/Qwen3-8B}"
ADAPTERS="${ADAPTERS:-}"
REF_ADAPTERS="${REF_ADAPTERS:-$ADAPTERS}"
RUN_NAME="${RUN_NAME:-hanabi-grpo-no-think-$(date +%Y%m%d_%H%M%S)}"
DATASET="${DATASET:-data/hanabi.grpo.jsonl}"
OUTPUT_DIR="${OUTPUT_DIR:-$ROOT_DIR/output/$RUN_NAME}"

HOST="${HOST:-127.0.0.1}"
PORTS="${PORTS:-8100,8101,8102,8103,8104}"
VLLM_SERVER_GROUP_PORT="${VLLM_SERVER_GROUP_PORT:-}"
ROLLOUT_GPU_LIST="${ROLLOUT_GPU_LIST:-0,1,2,3,4}"
TRAIN_GPU_LIST="${TRAIN_GPU_LIST:-5,6,7,8,9}"

SWIFT_BIN="${SWIFT_BIN:-$ROOT_DIR/.venv-grpo/bin/swift}"
ENABLE_THINKING="${ENABLE_THINKING:-false}"
MAX_TURNS="${MAX_TURNS:-150}"
HANABI_CTX_MAX_TURNS="${HANABI_CTX_MAX_TURNS:-1}"
HANABI_CTX_KEEP_SYSTEM="${HANABI_CTX_KEEP_SYSTEM:-true}"

VLLM_MAX_MODEL_LEN="${VLLM_MAX_MODEL_LEN:-8192}"
VLLM_MAX_NUM_SEQS="${VLLM_MAX_NUM_SEQS:-16}"
VLLM_ENABLE_LORA="${VLLM_ENABLE_LORA:-true}"
VLLM_MAX_LORA_RANK="${VLLM_MAX_LORA_RANK:-8}"
VLLM_USE_ASYNC_ENGINE="${VLLM_USE_ASYNC_ENGINE:-true}"
VLLM_SERVER_TIMEOUT="${VLLM_SERVER_TIMEOUT:-1800}"
HEALTH_RETRIES="${HEALTH_RETRIES:-180}"
HEALTH_SLEEP_SEC="${HEALTH_SLEEP_SEC:-2}"

MAX_LENGTH="${MAX_LENGTH:-8192}"
MAX_COMPLETION_LENGTH="${MAX_COMPLETION_LENGTH:-256}"
NUM_GENERATIONS="${NUM_GENERATIONS:-8}"
GENERATION_BATCH_SIZE="${GENERATION_BATCH_SIZE:-40}"
MAX_STEPS="${MAX_STEPS:-1000}"
SAVE_STEPS="${SAVE_STEPS:-20}"
LEARNING_RATE="${LEARNING_RATE:-5e-6}"
BETA="${BETA:-0.04}"
ASYNC_GENERATE="${ASYNC_GENERATE:-false}"
COMPLETION_LENGTH_LIMIT_SCOPE="${COMPLETION_LENGTH_LIMIT_SCOPE:-per_round}"
VLLM_SERVER_PASS_DATASET="${VLLM_SERVER_PASS_DATASET:-true}"
SOFT_MAX_LENGTH="${SOFT_MAX_LENGTH:-}"
OVERLONG_FILTER="${OVERLONG_FILTER:-}"
LOG_COMPLETIONS="${LOG_COMPLETIONS:-true}"
REPORT_TO="${REPORT_TO:-wandb}"

NCCL_P2P_DISABLE="${NCCL_P2P_DISABLE:-1}"
NCCL_IB_DISABLE="${NCCL_IB_DISABLE:-1}"
FORCE_RESTART="${FORCE_RESTART:-true}"

if [ ! -x "$SWIFT_BIN" ]; then
  echo "swift binary not found at '$SWIFT_BIN'. Create the GRPO env first or set SWIFT_BIN explicitly." >&2
  exit 1
fi

if [ ! -d "$MODEL" ]; then
  MODEL="Qwen/Qwen3-8B"
fi

if [ -z "${ADAPTERS//[[:space:]]/}" ]; then
  echo "ADAPTERS is required. Point it to the no-think SFT LoRA checkpoint or downloaded ModelScope adapter." >&2
  exit 1
fi

if [ -z "${REF_ADAPTERS//[[:space:]]/}" ]; then
  echo "REF_ADAPTERS resolved to empty. Set ADAPTERS or REF_ADAPTERS explicitly." >&2
  exit 1
fi

cd "$ROOT_DIR"

if [ -z "$VLLM_SERVER_GROUP_PORT" ]; then
  VLLM_SERVER_GROUP_PORT="$(
    awk -F, '{for (i = 1; i <= NF; ++i) printf "%s%d", (i > 1 ? "," : ""), 63051 + i - 1}' <<< "$PORTS"
  )"
fi

FORCE_RESTART="$FORCE_RESTART" \
SESSION="$ROLLOUT_SESSION" \
MODEL="$MODEL" \
HOST="$HOST" \
PORTS="$PORTS" \
GPU_LIST="$ROLLOUT_GPU_LIST" \
ENABLE_THINKING="$ENABLE_THINKING" \
MAX_TURNS="$MAX_TURNS" \
HANABI_CTX_MAX_TURNS="$HANABI_CTX_MAX_TURNS" \
HANABI_CTX_KEEP_SYSTEM="$HANABI_CTX_KEEP_SYSTEM" \
VLLM_MAX_MODEL_LEN="$VLLM_MAX_MODEL_LEN" \
VLLM_MAX_NUM_SEQS="$VLLM_MAX_NUM_SEQS" \
VLLM_ENABLE_LORA="$VLLM_ENABLE_LORA" \
VLLM_MAX_LORA_RANK="$VLLM_MAX_LORA_RANK" \
VLLM_USE_ASYNC_ENGINE="$VLLM_USE_ASYNC_ENGINE" \
SWIFT_BIN="$SWIFT_BIN" \
NCCL_P2P_DISABLE="$NCCL_P2P_DISABLE" \
NCCL_IB_DISABLE="$NCCL_IB_DISABLE" \
bash tools/tmux/start_hanabi_rollout_tmux.sh

IFS=',' read -r -a _port_arr <<< "$PORTS"
for port in "${_port_arr[@]}"; do
  ok=false
  for ((i = 1; i <= HEALTH_RETRIES; i++)); do
    if curl -fsS "http://${HOST}:${port}/health/" >/dev/null 2>&1; then
      ok=true
      break
    fi
    sleep "$HEALTH_SLEEP_SEC"
  done
  if [ "$ok" != "true" ]; then
    echo "rollout server health check failed: ${HOST}:${port}" >&2
    exit 1
  fi
done

FORCE_RESTART="$FORCE_RESTART" \
SESSION="$TRAIN_SESSION" \
MODEL="$MODEL" \
DATASET="$DATASET" \
RUN_NAME="$RUN_NAME" \
OUTPUT_DIR="$OUTPUT_DIR" \
CUDA_VISIBLE_DEVICES="$TRAIN_GPU_LIST" \
NPROC_PER_NODE="$(awk -F, '{print NF}' <<< "$TRAIN_GPU_LIST")" \
VLLM_SERVER_HOST="$(awk -F, -v h="$HOST" '{for (i = 1; i <= NF; ++i) printf "%s%s", (i > 1 ? "," : ""), h}' <<< "$PORTS")" \
VLLM_SERVER_PORT="$PORTS" \
VLLM_SERVER_GROUP_PORT="$VLLM_SERVER_GROUP_PORT" \
VLLM_SERVER_TIMEOUT="$VLLM_SERVER_TIMEOUT" \
NUM_GENERATIONS="$NUM_GENERATIONS" \
GENERATION_BATCH_SIZE="$GENERATION_BATCH_SIZE" \
MAX_LENGTH="$MAX_LENGTH" \
MAX_COMPLETION_LENGTH="$MAX_COMPLETION_LENGTH" \
MAX_STEPS="$MAX_STEPS" \
SAVE_STEPS="$SAVE_STEPS" \
MAX_TURNS="$MAX_TURNS" \
LOG_COMPLETIONS="$LOG_COMPLETIONS" \
REPORT_TO="$REPORT_TO" \
SWIFT_BIN="$SWIFT_BIN" \
ADAPTERS="$ADAPTERS" \
REF_ADAPTERS="$REF_ADAPTERS" \
ENABLE_THINKING="$ENABLE_THINKING" \
LEARNING_RATE="$LEARNING_RATE" \
BETA="$BETA" \
ASYNC_GENERATE="$ASYNC_GENERATE" \
COMPLETION_LENGTH_LIMIT_SCOPE="$COMPLETION_LENGTH_LIMIT_SCOPE" \
VLLM_SERVER_PASS_DATASET="$VLLM_SERVER_PASS_DATASET" \
SOFT_MAX_LENGTH="$SOFT_MAX_LENGTH" \
OVERLONG_FILTER="$OVERLONG_FILTER" \
NCCL_P2P_DISABLE="$NCCL_P2P_DISABLE" \
NCCL_IB_DISABLE="$NCCL_IB_DISABLE" \
bash tools/tmux/start_hanabi_train_long_tmux.sh

echo
echo "Hanabi no-think GRPO started."
echo "Run name:        $RUN_NAME"
echo "Rollout session: $ROLLOUT_SESSION"
echo "Train session:   $TRAIN_SESSION"
echo "Adapter:         $ADAPTERS"
echo "Ref adapter:     $REF_ADAPTERS"
