#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

SESSION="${SESSION:-hanabi_train_long}"
MODEL="${MODEL:-/workspace/models/Qwen3-8B}"
DATASET="${DATASET:-data/hanabi.grpo.jsonl}"
RUN_NAME="${RUN_NAME:-hanabi-grpo-long-$(date +%Y%m%d_%H%M%S)}"
OUTPUT_DIR="${OUTPUT_DIR:-$ROOT_DIR/output/$RUN_NAME}"
LOG_DIR="${LOG_DIR:-$ROOT_DIR/logs/tmux/$SESSION}"

CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-5,6,7,8,9}"
NPROC_PER_NODE="${NPROC_PER_NODE:-5}"
VLLM_SERVER_HOST="${VLLM_SERVER_HOST:-127.0.0.1,127.0.0.1,127.0.0.1,127.0.0.1,127.0.0.1}"
VLLM_SERVER_PORT="${VLLM_SERVER_PORT:-8100,8101,8102,8103,8104}"
VLLM_SERVER_GROUP_PORT="${VLLM_SERVER_GROUP_PORT:-63051,63052,63053,63054,63055}"
VLLM_SERVER_TIMEOUT="${VLLM_SERVER_TIMEOUT:-1800}"

NUM_GENERATIONS="${NUM_GENERATIONS:-10}"
GENERATION_BATCH_SIZE="${GENERATION_BATCH_SIZE:-50}"
MAX_LENGTH="${MAX_LENGTH:-16384}"
MAX_COMPLETION_LENGTH="${MAX_COMPLETION_LENGTH:-13000}"
MAX_STEPS="${MAX_STEPS:-1000}"
SAVE_STEPS="${SAVE_STEPS:-20}"
LOG_COMPLETIONS="${LOG_COMPLETIONS:-true}"
REPORT_TO="${REPORT_TO:-wandb}"
TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC="${TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC:-3600}"
EXTRA_SWIFT_ARGS="${EXTRA_SWIFT_ARGS:---vllm_server_pass_dataset true}"
# Avoid default torchrun rendezvous port conflict (29500) with stale workers.
MASTER_PORT="${MASTER_PORT:-$((20000 + ($(date +%s) % 20000)))}"
NCCL_P2P_DISABLE="${NCCL_P2P_DISABLE:-1}"
NCCL_IB_DISABLE="${NCCL_IB_DISABLE:-1}"

FORCE_RESTART="${FORCE_RESTART:-false}"

if [ ! -d "$MODEL" ]; then
  MODEL="Qwen/Qwen3-8B"
fi

is_true() {
  case "${1:-}" in
    1|true|TRUE|yes|YES|on|ON) return 0 ;;
    *) return 1 ;;
  esac
}

mkdir -p "$LOG_DIR" "$OUTPUT_DIR"
log_file="$LOG_DIR/${RUN_NAME}.log"

if tmux has-session -t "$SESSION" 2>/dev/null; then
  if is_true "$FORCE_RESTART"; then
    tmux kill-session -t "$SESSION"
  else
    echo "tmux session '$SESSION' already exists. Set FORCE_RESTART=true to recreate." >&2
    exit 0
  fi
fi

cmd="cd \"$ROOT_DIR\" && MODEL=\"$MODEL\" DATASET=\"$DATASET\" OUTPUT_DIR=\"$OUTPUT_DIR\" CUDA_VISIBLE_DEVICES=\"$CUDA_VISIBLE_DEVICES\" NPROC_PER_NODE=\"$NPROC_PER_NODE\" VLLM_SERVER_HOST=\"$VLLM_SERVER_HOST\" VLLM_SERVER_PORT=\"$VLLM_SERVER_PORT\" VLLM_SERVER_GROUP_PORT=\"$VLLM_SERVER_GROUP_PORT\" VLLM_SERVER_TIMEOUT=\"$VLLM_SERVER_TIMEOUT\" NUM_GENERATIONS=\"$NUM_GENERATIONS\" GENERATION_BATCH_SIZE=\"$GENERATION_BATCH_SIZE\" MAX_LENGTH=\"$MAX_LENGTH\" MAX_COMPLETION_LENGTH=\"$MAX_COMPLETION_LENGTH\" MAX_STEPS=\"$MAX_STEPS\" SAVE_STEPS=\"$SAVE_STEPS\" LOG_COMPLETIONS=\"$LOG_COMPLETIONS\" REPORT_TO=\"$REPORT_TO\" RUN_NAME=\"$RUN_NAME\" TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC=\"$TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC\" MASTER_PORT=\"$MASTER_PORT\" EXTRA_SWIFT_ARGS=\"$EXTRA_SWIFT_ARGS\" NCCL_P2P_DISABLE=\"$NCCL_P2P_DISABLE\" NCCL_IB_DISABLE=\"$NCCL_IB_DISABLE\" bash tools/train/train_grpo_hanabi_server_simple.sh 2>&1 | tee -a \"$log_file\""

tmux new-session -d -s "$SESSION" -n train "$cmd"
tmux set-option -t "$SESSION" remain-on-exit on >/dev/null

echo "Started training tmux session: $SESSION"
echo "Run name: $RUN_NAME"
echo "MASTER_PORT: $MASTER_PORT"
echo "NCCL_P2P_DISABLE: $NCCL_P2P_DISABLE"
echo "NCCL_IB_DISABLE: $NCCL_IB_DISABLE"
echo "Output dir: $OUTPUT_DIR"
echo "Log file: $log_file"
echo "Attach: tmux attach -t $SESSION"
